GET http://localhost:3100/study

###

GET http://localhost:3100/study/52460725-f825-409e-9bfb-f5c0b5452420

###

POST http://localhost:3100/study
Content-Type: application/json

{
  "nickname": "studyMaster",
  "studyname": "Math Enthusiasts",
  "description": "A group for people passionate about math.",
  "password": "secure123",
  "point": 10,
  "img": "image1.png",
  "tags": ["math", "enthusiasts"]
}
###
POST http://localhost:3100/study/9dfdd5da-34ca-4370-b0be-8184fbfcf768/todo
Content-Type: application/json

{
  "text": "Complete React hooks tutorial"
}


###

POST http://localhost:3100/study/1cd13ed4-4a7e-41ec-a06c-7d3914b36b7c/emoticon
Content-Type: application/json

{
  "emoticon": "😊
}
###
