GET http://localhost:3100/study

###

GET http://localhost:3100/study/bf794db0-3877-40f7-a6c9-96676380a298

###

POST http://localhost:3100/study
Content-Type: application/json

{
  "nickname": "studyMaster",
  "studyname": "Math Enthusiasts",
  "description": "A group for people passionate about math.",
  "password": "secure123",
  "point": 10,
  "img": "image1.png",
  "tags": ["math", "enthusiasts"]
}
###
POST http://localhost:3100/study/bf794db0-3877-40f7-a6c9-96676380a298/todo
Content-Type: application/json

{
  "text": "청소하기"
}


###

POST http://localhost:3100/study/caa2663a-879c-4b21-8c8f-63ab9a7d1c28/emoticon
Content-Type: application/json

{
  "emoticon": "😇"
}
###
GET http://localhost:3100/study/bf794db0-3877-40f7-a6c9-96676380a298/todo
###
DELETE http://localhost:3100/study/bf794db0-3877-40f7-a6c9-96676380a298/todo/13

###
POST http://localhost:3100/study/bf794db0-3877-40f7-a6c9-96676380a298/todos
Content-Type: application/json

[
  {
    "id": 14,
    "text": "청소하기",
    "createdAt": "2025-01-05T07:00:32.455Z",
    "updatedAt": "2025-01-05T07:00:32.455Z",
    "done": false,
    "studyGroupId": "bf794db0-3877-40f7-a6c9-96676380a298"
  },
  {
    "id": 16,
    "text": "ㅁㄴㅁㄴㅇㅇ",
    "createdAt": "2025-01-05T08:11:37.440Z",
    "updatedAt": "2025-01-05T08:11:37.440Z",
    "done": false,
    "studyGroupId": "bf794db0-3877-40f7-a6c9-96676380a298"
  },
  {
    "id": 22,
    "text": "ㅁㄴㅇㅁㄴㅇ",
    "createdAt": "2025-01-05T08:33:12.405Z",
    "updatedAt": "2025-01-05T08:33:12.405Z",
    "done": false,
    "studyGroupId": "bf794db0-3877-40f7-a6c9-96676380a298"
  },
  {
    "id": 23,
    "text": "ㅁㄴㅇ",
    "createdAt": "2025-01-05T08:36:03.515Z",
    "updatedAt": "2025-01-05T08:36:03.515Z",
    "done": false,
    "studyGroupId": "bf794db0-3877-40f7-a6c9-96676380a298"
  }
]


