# Todo 목록 가져오기 (페이지네이션 포함)
GET http://localhost:3100/todos?page=1&pageSize=5
Headers:
  Accept: application/json

# Todo ID로 조회
GET http://localhost:3100/todos/1
Headers:
  Accept: application/json

# 새로운 Todo 추가
POST http://localhost:3100/todos
Headers:
  Content-Type: application/json
Body:
{
  "text": "새로운 Todo 추가"
}

# Todo 삭제
DELETE http://localhost:3100/todos/1
Headers:
  Accept: application/json
